//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CentroCultural.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matricula
    {
        public long IdMatricula { get; set; }
        public string Cedula { get; set; }
        public Nullable<long> IdCurso { get; set; }
        public Nullable<long> IdModalidad { get; set; }
        public Nullable<long> IdNivel { get; set; }
        public Nullable<long> IdHorario { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<System.DateTime> FechaMatricula { get; set; }
        public Nullable<int> DiaPago { get; set; }
        public string Comentario { get; set; }
        public Nullable<long> IdEstatus { get; set; }
    }
}
