//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CentroCultural.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nota
    {
        public long IdNota { get; set; }
        public Nullable<long> IdGrupo { get; set; }
        public Nullable<long> IdUsuario { get; set; }
        public Nullable<long> IdOficinas { get; set; }
        public Nullable<decimal> Nota1 { get; set; }
        public Nullable<long> IdAgisnacion { get; set; }
        public Nullable<long> IdCurso { get; set; }
        public Nullable<long> IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Asignaciones Asignaciones { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual Oficina Oficina { get; set; }
    }
}
