//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CentroCultural.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoClientes
    {
        public long IdPagoCliente { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Motivo { get; set; }
        public string IdCliente { get; set; }
        public Nullable<long> IdCurso { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<long> IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    }
}
