//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CentroCultural.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public long IdUsuario { get; set; }
        public string Usuario1 { get; set; }
        public string PwUsuario { get; set; }
        public Nullable<long> IdOficina { get; set; }
        public string IdCliente { get; set; }
        public Nullable<long> IdRol { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaUltimaActividad { get; set; }
        public Nullable<long> IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<long> IdEstatus { get; set; }
    }
}
